name: CI - tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.11']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest -q
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    name: CI - tests

    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]

    jobs:
      test:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
            python: ['3.11']

        steps:
          - uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python }}

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install pytest

          - name: Run tests
            run: pytest -q
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Run linters
        run: |
          echo "No linters configured yet"
      - name: Run tests
        run: |
          echo "No tests configured yet"
name: CI - Ultramotion Manual   # Le nom "CI - Ultramotion Manual" rend explicite qu’il s’agit d’un workflow CI déclenché manuellement.

on:
  workflow_dispatch:   # ➜ Workflow déclenchable uniquement manuellement depuis GitHub. ➜ Aucun build automatique sur push/PR.

jobs:
  test:   # ➜ Conteneur principal des étapes à exécuter dans ce workflow.
    runs-on: ubuntu-latest   # ➜ Crée un job de test s’exécutant sur une machine Ubuntu.
    steps:   # ➜ Conteneur des actions à exécuter dans le job "test".

      - uses: actions/checkout@v4   # ➜ Clone automatiquement ton dépôt pour que le job puisse y accéder.

      - name: Set up Python            # ➜ Étape lisible dans les logs : préparation de l'environnement Python
        uses: actions/setup-python@v4  # ➜ Action officielle qui installe/configure Python pour le runner
        with:
          python-version: '3.11'   # ➜ Prépare un environnement Python 3.11 identique à ton conteneur local.

      - name: Install deps with uv     # ➜ Étape d’installation des dépendances Python via uv (rapide/déterministe)
        run: |
          pip install uv     # ➜ Installe l’outil uv dans l’env GitHub Actions avant le sync
          uv sync --frozen   # ➜ Installe `uv`, synchronise les dépendances définies dans `pyproject.toml` et `uv.lock`, et garantit une installation reproductible.

      - name: Run a smoke test         # ➜ Vérification minimale que l’environnement s’exécute correctement
        run: |
          python -c "print('✅ CI environment ready')"   # ➜ Effectue un test minimal pour vérifier la stabilité de l’environnement CI et confirmer que Python + uv sont correctement configurés.
